export const CONFIGURAR_ENVIOS = 'ENVIOS/CONFIGURAR_ENVIOS'
export const CONFIGURAR_ENVIOS_PAGINADOS = 'ENVIOS/CONFIGURAR_ENVIOS_PAGINADOS'
export const CONFIGURAR_DADOS_INICIAIS = 'ENVIOS/CONFIGURAR_DADOS_INICIAIS'
export const DELETAR_ENVIO = 'ENVIOS/DELETAR_ENVIO'
