export const CONFIGURAR_USUARIOS = 'USUARIOS/CONFIGURAR_USUARIOS'
export const CONFIGURAR_USUARIOS_PAGINADOS = 'USUARIOS/CONFIGURAR_USUARIOS_PAGINADOS'
export const CONFIGURAR_DADOS_INICIAIS = 'USUARIOS/CONFIGURAR_DADOS_INICIAIS'
export const DELETAR_USUARIO = 'USUARIOS/DELETAR_USUARIO'
