export default {
  //producao
  //url: "http://165.227.214.12:8000/api/",
  //desenvolvimento
  url: "https://frontend-empresasolucao.azurewebsites.net/api",
  perfil: [
    "Administrador",
    "Operador",
    "OperadorDeCheques",
    "ApenasVisualizacao",
  ],
  perfis: [
    { value: "0", name: "Administrador" },
    { value: "1", name: "Operador" },
    { value: "2", name: "OperadorDeCheques" },
    { value: "3", name: "ApenasVisualizacao" },
  ],
  situacao: ["Inativo", "Ativo"],
  bancos: [
    { value: "0", name: "Banco Do Brasil" },
    { value: "1", name: "Bradesco" },
    { value: "2", name: "Brb" },
    { value: "3", name: "Caixa" },
    { value: "4", name: "Hsbc" },
    { value: "5", name: "Itau" },
    { value: "6", name: "Mercantil Do Brasil" },
    { value: "7", name: "Santander" },
    { value: "8", name: "Sicoob" },
    { value: "9", name: "Outros" },
    { value: "10", name: "BancoReal" },
    { value: "11", name: "Baneste" },
  ],
  origens: [{ value: "0", name: "Itiquira" }, { value: "1", name: "Solução" }],
  situacaoDaOcorrencia: ["Resolvido", "Não Resolvido", "Agendado"],
  situacoesDaOcorrencia: [
    { value: "0", name: "Resolvido" },
    { value: "1", name: "Não Resolvido" },
    { value: "2", name: "Agendado" },
  ],
  categoria: [
    "Outros",
    "Contribuintes",
    "Gold",
    "Plus",
    "Remido Cancelado",
    "Remido Clube",
    "Remido Termas",
    "Remido Itiquira",
    "Titulos Sênior",
    "Vip",
    "Vivendas",
    "Vivendas Clube",
    "Boletos",
    "Cheque",
    "Nota Promissória",
  ],
  categorias: [
    { value: "0", name: "Outros" },
    { value: "1", name: "Contribuintes" },
    { value: "2", name: "Gold" },
    { value: "3", name: "Plus" },
    { value: "4", name: "RemidoCancelado" },
    { value: "5", name: "RemidoClube" },
    { value: "6", name: "RemidoTermas" },
    { value: "7", name: "RemidoItiquira" },
    { value: "8", name: "TitulosSenior" },
    { value: "9", name: "Vip" },
    { value: "10", name: "Vivendas" },
    { value: "11", name: "VivendasClube" },
    { value: "12", name: "Boletos" },
    { value: "13", name: "Cheque" },
    { value: "14", name: "NotaPromissoria" },
  ],
  tiposDeContato: [
    { value: "1", name: "Ligação" },
    { value: "2", name: "Whatsapp" },
    { value: "3", name: "E-mail" },
    { value: "4", name: "Sms" },
  ],
};
