export const CONFIGURAR_SOCIOS = "SOCIOS/CONFIGURAR_SOCIOS";
export const CONFIGURAR_SOCIOS_PAGINADOS = "SOCIOS/CONFIGURAR_SOCIOS_PAGINADOS";
export const CONFIGURAR_SOCIO = "SOCIOS/CONFIGURAR_SOCIO";
export const CONFIGURAR_DADOS_INICIAIS = "SOCIOS/CONFIGURAR_DADOS_INICIAIS";
export const CONFIGURAR_IMPORTACAO = "SOCIOS/CONFIGURAR_IMPORTACAO";
export const DELETAR_SOCIO = "SOCIOS/DELETAR_SOCIO";
